/**
 * Action types constants
 *
 * @type {Object}
 */
const ActionTypes = {
    /*
     * Application
     */
    INITIALIZE: 'INITIALIZE',
    PLACEHOLDER: 'PLACEHOLDER',
    TOGGLE_MENU: 'TOGGLE_MENU',
    /*
     * Labels
     */
    FETCH_LABELS_REQUEST: 'FETCH_LABELS_REQUEST',
    FETCH_LABELS_SUCCESS: 'FETCH_LABELS_SUCCESS',
    FETCH_LABELS_ERROR: 'FETCH_LABELS_ERROR',
    /*
     * Users
     */
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    DELETE_USER_REQUESTED: 'DELETE_USER_REQUESTED',
    DELETE_USER_CANCELED: 'DELETE_USER_CANCELED',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_ERROR: 'ADD_USER_ERROR',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    FILTER_USER: 'FILTER_USER',
    SORT_USER: 'SORT_USER',
    /*
     * Notification
     */
    NOTIFICATION_HIDE: 'NOTIFICATION_HIDE'
};

export default ActionTypes;
