/**
 * Action types constants
 *
 * @type {Object}
 */
const ActionTypes = {
    /*
     * Application
     */
    INITIALIZE: 'INITIALIZE',
    PLACEHOLDER: 'PLACEHOLDER',
    TOGGLE_MENU: 'TOGGLE_MENU',
    /*
     * Users
     */
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    UPDATE_USERS_REQUEST: 'UPDATE_USERS_REQUEST',
    UPDATE_USERS_ERROR: 'UPDATE_USERS_ERROR',
    UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
    DELETE_USERS_REQUESTED: 'DELETE_USERS_REQUESTED',
    DELETE_USERS_REQUEST: 'DELETE_USERS_REQUEST',
    DELETE_USERS_ERROR: 'DELETE_USERS_ERROR',
    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    FILTER_USER: 'FILTER_USER',
    SORT_USER: 'SORT_USER'
};

export default ActionTypes;
