/**
 * Action types constants
 *
 * @type {Object}
 */
const ActionTypes = {
    INITIALIZE: 'INITIALIZE',
    PLACEHOLDER: 'PLACEHOLDER',
    TOGGLE_MENU: 'TOGGLE_MENU',
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FILTER_USER: 'FILTER_USER',
    SORT_USER: 'SORT_USER'
};

export default ActionTypes;
