sudo: false
language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run eslint lint
  - yarn run test

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
